### ISSUE TITLE
Add support for remote path configuration

### ISSUE THREAD

**Issue by PierreR** [zimbatm/vagrant-nixos-plugin#10]
I would like to use the plugin to provision multiple vms. In that regards, I want to be able to load the nixos configuration from a remove (SCM) file:

```
config.vm.provision :nixos,
  run: 'always',
  path: “http://repo.lan/projects/devbox/browse/configuration.nix?12345&raw”,
  include: true
```

It is fine if path only support the `github` scheme"https://raw.githubusercontent.com/devbox/master/configuration.nix"

With this in place I can update the nixos configuration more easily; I don't need to clone/pull a repo on each developer boxes.

Do you think the use case is valid ?

**Comment by zimbatm** [comment]
Yes that's a good idea. You could add a config.url option and fetch that on provisioning. See lib/varant-nixos/provisioner.rb around line 13. If you implement something like that I'm happy to merge it make a quick release.

**Comment by PierreR** [comment]
I have actually ended up managing the extension of the box with a shell vagrant provisioner. For my use case, I don't thing the nixos plugin would ease the pain.

I also had to deal with a way to update devbox machines while provisioning in a transparent way. If you are curious the code is [here](https://github.com/CIRB/devbox/blob/master/Vagrantfile).
