### ISSUE TITLE
warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by zagy** [zimbatm/vagrant-nixos-plugin#12]
Recently (ruby 2.4) I get the following output from vagrant:

/Users/zagy/.vagrant.d/gems/2.4.3/gems/vagrant-nixos-plugin-0.2.1/lib/vagrant-nixos/nix.rb:78: warning: constant ::Fixnum is deprecated

From http://www.a-k-r.org/pub/2016-09-08-rubykaigi-unified-integer.pdf I think "Fixnum" needs to be changed to "Integer". But now knowing ruby very well I wouldn't even know how to test that :/

**Comment by zimbatm** [comment]
Can you try and replace `Fixnum` by `Integer` on that line? It should be backward-compatible until Ruby 2.3 at least. Integer has been added as a parent class of Fixnum some time before.

```
$ nix run nixpkgs.ruby_2_3 -c irb
irb(main):001:0> 1.class.ancestors
=> [Fixnum, Integer, Numeric, Comparable, Object, Kernel, BasicObject]
$ nix run nixpkgs.ruby_2_4 -c irb
irb(main):001:0> 1.class.ancestors
=> [Integer, Numeric, Comparable, Object, Kernel, BasicObject]
```

**Comment by ctheune** [comment]
See #13 the change.

[edit: fat fingers]

**Comment by zimbatm** [comment]
thanks @ctheune

**Comment by zagy** [comment]
@zimbatm While this is fixed, a new release is missing. Could create one?

**Comment by zimbatm** [comment]
done!

**Comment by zagy** [comment]
Thank you!
