### ISSUE TITLE
Dependency conflict in 'fog-core' between vagrant-libvirt and vagrant-nixos-plugin

### ISSUE THREAD

**Issue by joseph-long** [zimbatm/vagrant-nixos-plugin#14]
When trying to install on Ubuntu 18.04, I get the following error:

```
$ vagrant plugin install vagrant-nixos-plugin
Installing the 'vagrant-nixos-plugin' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies fog-core (~> 1.43.0) and fog-core (= 1.45.0)
  Activated fog-core-1.45.0
  which does not match conflicting dependency (~> 1.43.0)

  Conflicting dependency chains:
    fog-core (= 1.45.0), 1.45.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.41 activated, depends on
    fog-core (~> 1.43.0)
```

**Comment by zimbatm** [comment]
This plugin doesn't have any dependencies, not sure why fog-core is being installed here.

Is it possible that the vagrant-libvirt plugin is the one causing problems?

**Comment by joseph-long** [comment]
Yeah, I was about to come back and close this. That does seem to be the case...

**Comment by 4levels** [comment]
Just for future references: this can be resolved in debian by removing the `vagrant` version installed by `apt` and use the `.deb` downloadable version from the [vagrant website](https://www.vagrantup.com/) (currently v2.2.5)
