### ISSUE TITLE
error running 'mv /tmp/vagrant-provision.nix /etc/nixos/vagrant-provision.nix'

### ISSUE THREAD

**Issue by bbigras** [zimbatm/vagrant-nixos-plugin#15]
I use virtualbox and I disabled the shared folders with `config.vm.synced_folder '.', '/vagrant', disabled: true` since the box wouldn't start otherwise.

```yaml
  config.vm.provision :nixos, expression: {
    services: {
      nginx: {
        enable: true,
      }
    }
  }
```

```
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'nixbox64'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vm-nix_default_1574441637593_12507
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Running provisioner: nixos...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv /tmp/vagrant-provision.nix /etc/nixos/vagrant-provision.nix

Stdout from the command:



Stderr from the command:
```

**Comment by stefandeml** [comment]
yeah, running into the same error on my end. 
`Running provisioner: nixos` fails for the example config in the repo.
@zimbatm any pointer where to look to fix that issue?

**Comment by stefandeml** [comment]
Update:

Using the vagrant box on vagrantcloud "nixos/nixos-16.09-x86_64" instead of the one created by nixbox packer solved the issue.  Hence I think it's a issue with nixbox and not this plugin. Any idea what could be the reason?

**Comment by zimbatm** [comment]
Is it possible that `/etc/nixos` doesn't exist in the new image? The plugin assumes that it's there:

https://github.com/nix-community/vagrant-nixos-plugin/blob/b79bac22e85c39f2eccdc0aad591794432e493f4/lib/vagrant-nixos/provisioner.rb#L94-L111

**Comment by bbigras** [comment]
`/etc/nixos` does exist if I check with `vagrant ssh` just after getting the error message:

![image](https://user-images.githubusercontent.com/24027/69563102-74514300-0f7e-11ea-9629-2e726115b4b5.png)

**Comment by zimbatm** [comment]
What about `/tmp/vagrant-provision.nix`, is it still there?

Typically what I would do is edit the ruby code to add some `puts` debugging. It looks like line 103 succeeded and the file got uploaded. Then for some reason the mv command failed. It could be a number of issues.

You could change line 107 to add `-v` flag for more verbosity from the tool: `comm.sudo("mv -v #{source} #{target}") `

**Comment by bbigras** [comment]
> What about /tmp/vagrant-provision.nix, is it still there?

Yes.

![image](https://user-images.githubusercontent.com/24027/69566805-ed07cd80-0f85-11ea-9c8e-17b5e96d792e.png)

Can the script handle the sudo password? `comm.sudo("echo test")` doesn't work either.

**Comment by bbigras** [comment]
I seem able to run `vagrant provision` if I set NOPASSWD in the sudoer file.

**Comment by zimbatm** [comment]
that smells like a regression in the image. The vagrant user is supposed to have password-less sudo access.

**Comment by zimbatm** [comment]
the vagrant user is supposed to belong to the `wheel` group and that group is supposed to have NOPASSWD in the sudoers:

https://github.com/nix-community/nixbox/blob/12d37d11d1651293d6518ae1cb806c6e0f074b67/scripts/configuration.nix#L45-L75

**Comment by stefandeml** [comment]
> I seem able to run `vagrant provision` if I set NOPASSWD in the sudoer file.

yeah that seem so fix provisioning. However, the `/vagrant` folder still is not mounted correctly.

**Comment by stefandeml** [comment]
This PR should fix the issue: https://github.com/nix-community/nixbox/pull/53

**Comment by zimbatm** [comment]
nice, thanks for debugging this!
